// Generated by https://quicktype.io

import 'package:flutter/rendering.dart';

class DescModel {
  int? id;
  String? descriptionRaw;

  DescModel({
    this.id,
    this.descriptionRaw,
  });

  factory DescModel.fromMap(Map<String,dynamic> map){
    return DescModel(
      id : map['id'],
      descriptionRaw : map['description_raw'] 
    );
  }
}



