// Generated by https://quicktype.io


import 'package:app_juegos/models/platformElement_model.dart';
import 'package:flutter/rendering.dart';

import 'genre_model.dart';

class GamesModel {
  int? id;
  String? name;
  String? released;
  String? backgroundImage;
  double? rating;
  int? metacritic;
  int? playtime;
  List<PlatformElement>? platforms;
  List<Genre>? genres;

  GamesModel({
    this.id,
    this.name,
    this.released,
    this.backgroundImage,
    this.rating,
    this.metacritic,
    this.playtime,
    this.platforms,
    this.genres,
  });

  factory GamesModel.fromMap(Map<String,dynamic> map){
    return GamesModel(
      id : map['id'],
      name: map['name'],
      released: map['released'],
      backgroundImage: map['background_image'],
      rating: map['rating'],
      metacritic: map['metacritic'],
      playtime: map['playtime'],
      platforms: map['platforms'] == null ? null :  (map['platforms'] as List).map((i) => PlatformElement.fromMap(i)).toList(),
      genres: (map['genres'] as List).map((i) => Genre.fromMap(i)).toList()
    );
  }
}








