// Generated by https://quicktype.io

class ImagesModel {
  int? id;
  String? image;

  ImagesModel({
    this.id,
    this.image,
  });

  factory ImagesModel.fromMap(Map<String,dynamic> map){
    return ImagesModel(
      id : map['id'],
      image : map['image'] 
    );
  }
}
